### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by crypticmind** [Banno/sbt-license-plugin#1]
The download link for the plugin gives an "access denied" error.

http://cloud.github.com/downloads/T8Webware/sbt-license-plugin/sbt-license-plugin-0.0.2.jar

```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>576EA50A53E2C424</RequestId>
    <HostId>hz9wRUyvo0yD6qy8oH6KjqWzYfBvDd1p1Nx4XvM23mdmExWRJWvE0Yn7DP5kUF8B</HostId>
</Error>
```

**Comment by adamdecaf** [comment]
This should be fixed now. (Check the readme) Sorry I didn't update this issue.
