### ISSUE TITLE
problems formatting license headers on windows.

### ISSUE THREAD

**Issue by NicolasRouquette** [Banno/sbt-license-plugin#12]
This plugin has been working fine for my development (MacOSX).
A colleague began using my project which is configured to use this plugin to format our sources. His development machine runs Windows7 64bit.
We checked out the project from SVN and when we ran SBT (0.13.7), the formatting of the licenses erased the file contents; afterwards, there is just the license header itself.

Has anyone experienced this peculiar behavior on windows?

**Comment by CharlesHD** [comment]
I used it on windows machine once or twice. But that worked just fine. Using SBT 0.13.5 though but this shouldn't change a crap.
Was it on scala sources ?

**Comment by adamdecaf** [comment]
I don't really have a windows machine to test, but if I remember right this project just splits on `\n`. Doesn't windows use `\r` instead?
